# Generated by Django 4.2 on 2023-04-15 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("repo_sync", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="content",
        ),
        migrations.AddField(
            model_name="repository",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="repositories/"),
        ),
        migrations.AddField(
            model_name="repository",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="file",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="repo_sync.repository",
            ),
        ),
    ]
